#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 1.1.1.{build}
install:
  - git clone https://github.com/PowerShell/DscResource.Tests
  - git clone https://github.com/Microsoft/PowerStig.Tests
  - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
  - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
  - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\PowerStig.Tests\PowerStig.Tests.psd1"
  - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
  - ps: Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @()

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
before_deploy:
  - ps: PowerStig.Tests\Invoke-AppveyorAfterTestTask

for:
-
  branches:
    only:
      - master

  deploy:
    - provider: Environment
      name: Test PS Gallery
      on:
        appveyor_repo_tag: true
