#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 1.0.0.{build}
install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - git clone https://github.com/Microsoft/PowerStig.Tests
    - ps core: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps core: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps core: Import-Module "$env:APPVEYOR_BUILD_FOLDER\PowerStig.Tests\PowerStig.Tests.psd1"
    - ps core: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps core: |
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @()

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
before_deploy:
    - ps core: |
        PowerStig.Tests\Invoke-AppveyorAfterTestTask

deploy:
  - provider: Environment
    name: Test PS Gallery
    on:
      branch: master

  - provider: Environment
    name: Test PS Gallery
    on:
      appveyor_repo_tag: true
